// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7cDclXBLRenhYQsbUde7bodMvJ6k6sZg',
    appId: '1:807056065267:web:054b7237a8edc1f678ed86',
    messagingSenderId: '807056065267',
    projectId: 'tasker-g1',
    authDomain: 'tasker-g1.firebaseapp.com',
    storageBucket: 'tasker-g1.appspot.com',
    measurementId: 'G-33KPY4J7XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfLqtD-7PbQYI3qC-9zIYfnACm1D2HfW0',
    appId: '1:807056065267:android:b917b45a50a45ef478ed86',
    messagingSenderId: '807056065267',
    projectId: 'tasker-g1',
    storageBucket: 'tasker-g1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOk50DzQmaSNZqmcUI_EXvZDzSQFgzfac',
    appId: '1:807056065267:ios:da3dedcd57cc5ff678ed86',
    messagingSenderId: '807056065267',
    projectId: 'tasker-g1',
    storageBucket: 'tasker-g1.appspot.com',
    androidClientId: '807056065267-dhgl16u54qm120tefjf6deooa6m21enr.apps.googleusercontent.com',
    iosClientId: '807056065267-869g0lca8luihccbofoegrlt7d6b1olf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOk50DzQmaSNZqmcUI_EXvZDzSQFgzfac',
    appId: '1:807056065267:ios:da3dedcd57cc5ff678ed86',
    messagingSenderId: '807056065267',
    projectId: 'tasker-g1',
    storageBucket: 'tasker-g1.appspot.com',
    androidClientId: '807056065267-dhgl16u54qm120tefjf6deooa6m21enr.apps.googleusercontent.com',
    iosClientId: '807056065267-869g0lca8luihccbofoegrlt7d6b1olf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasker',
  );
}
